#upstream phpfpm {
    #server unix:/var/run/php5-fpm.sock;
    #avoid sockets for nginx-fpm on Linux, they are good for BSD
#    server 127.0.0.1:9000;
#}

server {
    listen 80;
    listen [::]:80;
    server_name ~^(.*\.)*ssb-pro\.test$;

    return 301 https://$host$request_uri;
}

 server {
     listen 443 ssl http2;
     listen [::]:443 ssl http2;
     server_name ~^(.*\.)*ssb-pro\.test$;
     index index.php index.html;
     root /var/www/public/;    

     error_log /var/log/nginx/error.log;
     access_log /var/log/nginx/access.log;

     ssl_certificate      /etc/nginx/certs/ssb-pro.test/cert.pem;
     ssl_certificate_key  /etc/nginx/certs/ssb-pro.test/key.pem;

     location ~ ^/.+\.php(/|$) {
        proxy_pass http://php:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
     }

    #  location ~ ^/.+\.php(/|$) {
    #     # Pass the request to the host "php" and port 9000 (default PHP-FPM port)
    #     fastcgi_pass  php:9000;
	# 	# Include the default NGINX FastCGI Parameters
    #     include       fastcgi_params;
	# 	# Define one additional parameter telling PHP-FPM where to find the file
    #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    # }

    # location ~ \.php$ {
    #     try_files $uri =404;
    #     fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #     fastcgi_pass php:9000;
    #     fastcgi_index index.php;
    #     include fastcgi_params;
    #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    #     fastcgi_param PATH_INFO $fastcgi_path_info;
    # }
 }

server {
    listen 80;
    listen [::]:80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ~. "";
    index index.php index.html;
    root /var/www/public/;

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    ssl_certificate      /etc/nginx/certs/$ssl_server_name/cert.pem;
    ssl_certificate_key  /etc/nginx/certs/$ssl_server_name/key.pem;

    #location / {
    #    proxy_pass http://php:9000;
    #    proxy_set_header Host $host;
    #    proxy_set_header X-Real-IP $remote_addr;
    #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #    proxy_set_header X-Forwarded-Proto https;
    #    proxy_set_header Upgrade $http_upgrade;
    #    proxy_set_header Connection 'upgrade';
    #}

    location ~ ^/.+\.php(/|$) {
        proxy_pass http://php:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
    }

    # location ~ ^/.+\.php(/|$) {
    #     # Pass the request to the host "php" and port 9000 (default PHP-FPM port)
    #     fastcgi_pass  php:9000;
	# 	# Include the default NGINX FastCGI Parameters
    #     include       fastcgi_params;
	# 	# Define one additional parameter telling PHP-FPM where to find the file
    #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    # }

    # location ~ \.php$ {
    #     try_files $uri =404;
    #     fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #     fastcgi_pass php:9000;
    #     fastcgi_index index.php;
    #     include fastcgi_params;
    #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    #     fastcgi_param PATH_INFO $fastcgi_path_info;
    # }
}